name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy LAMP app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script:
              cd production;
              git clone git@github.com:EminMammadzada/ContactsApp.git;
              echo 'Deployment to digital ocean was successful!';
         
